# Generated by Django 3.2 on 2022-02-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=25, verbose_name='Company Name')),
                ('caddress', models.CharField(max_length=250, verbose_name='Company Address')),
                ('cphone', models.CharField(max_length=25, verbose_name='Company Phoneno')),
                ('clicno', models.CharField(max_length=25, verbose_name='License No')),
                ('cphoto', models.ImageField(upload_to='images/')),
                ('cemail', models.EmailField(max_length=254, verbose_name='Company Email')),
                ('cpswd', models.CharField(max_length=25, verbose_name='Password')),
                ('status', models.CharField(default='N', max_length=20, verbose_name='Application Status')),
            ],
        ),
    ]
