# Generated by Django 3.2 on 2022-02-24 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufirst', models.CharField(max_length=25, verbose_name='First Name')),
                ('ulast', models.CharField(max_length=25, verbose_name='Last Name')),
                ('udob', models.DateField(default=datetime.date.today, verbose_name='Date of Brith')),
                ('uphone', models.CharField(max_length=25, verbose_name='Phone No')),
                ('uaadhar', models.CharField(max_length=25, verbose_name='Aadhaar No')),
                ('upawd', models.CharField(max_length=25, verbose_name='Password')),
                ('uemail', models.EmailField(max_length=254, verbose_name='User Email')),
                ('ugender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
