# Generated by Django 3.2 on 2022-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cphoto',
            field=models.ImageField(upload_to='images/', verbose_name='License Image'),
        ),
    ]
