# Generated by Django 3.2 on 2022-02-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_company_cphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cemail',
            field=models.EmailField(max_length=254, unique='true', verbose_name='Company Email'),
        ),
    ]
