# Generated by Django 3.2 on 2022-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_user_uemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cemail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='User Email'),
        ),
    ]
