# Generated by Django 3.2 on 2022-02-27 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20220225_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=25, verbose_name='Job Title')),
                ('jobdesc', models.TextField(verbose_name='Job Description')),
                ('jobtype', models.CharField(max_length=25, verbose_name='Job Type')),
                ('location', models.CharField(max_length=25, verbose_name='Location')),
                ('department', models.CharField(max_length=25, verbose_name='Department')),
                ('nov', models.IntegerField(verbose_name='Number of Vacancy')),
                ('tdate', models.DateField(default=datetime.date.today, verbose_name='Date of Posting')),
                ('edate', models.DateField(verbose_name='Valid Till')),
                ('cpname', models.CharField(max_length=25, verbose_name='Company Name')),
                ('cpdese', models.TextField(verbose_name='Company Description')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email for Enquiry')),
            ],
        ),
    ]
