# Generated by Django 3.2 on 2022-03-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_postjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='cpdese',
            field=models.TextField(verbose_name='Company description'),
        ),
    ]
