# Generated by Django 3.2 on 2022-03-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_auto_20220303_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email for Enquiry'),
        ),
    ]
