# Generated by Django 3.2 on 2022-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_postjob_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='status',
            field=models.CharField(default='N', max_length=15),
        ),
    ]
