# Generated by Django 3.2 on 2022-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_postjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='status',
            field=models.CharField(default='Not Applied', max_length=15),
        ),
    ]
