# Generated by Django 3.2 on 2022-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_alter_postjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
