# Generated by Django 3.2 on 2022-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_apply_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(default='NOT SELECTED', max_length=25),
        ),
    ]
