# Generated by Django 3.2 on 2022-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_alter_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uexp',
            field=models.CharField(default=0, max_length=25, verbose_name='Work Experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='ufile',
            field=models.FileField(default=0, max_length=254, upload_to='resume/', verbose_name='upload Resume'),
        ),
        migrations.AddField(
            model_name='user',
            name='uqual',
            field=models.CharField(default=0, max_length=25, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ugender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
    ]
