# Generated by Django 3.2 on 2022-05-17 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_auto_20220319_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cphone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Company Phoneno'),
        ),
    ]
